[project]
authors = ["Tomasz Danel <tomek@insitro.com>", "Benson Chen <bensonc@insitro.com>"]
channels = ["pyg", "pytorch", "nvidia", "conda-forge"]
description = "KinDEL: DNA-Encoded Library Dataset For Kinase Inhibitors"
name = "kindel"
platforms = ["osx-64", "linux-64", "win-64"]
version = "1.0.0"
license-file = "LICENSE.md"

[tasks]

[dependencies]
python = "<3.12"
redun = ">=0.22.0,<0.23"
xgboost = ">=2.1.1,<3"
pandas = ">=2.2.3,<3"
rdkit = ">=2024.3.6,<2025"
tqdm = ">=4.66.5,<5"
scikit-learn = ">=1.5.2,<2"
pyarrow = ">=17.0.0,<18"
numpy = "<2"
pytorch = ">=2.2.0,<3"
c-ares = "==1.32.3"
wandb = ">=0.17.3,<0.18"
pytorch-lightning = ">=2.4.0,<3"
pyg = ">=2.5.2,<3"
omegaconf = ">=2.3.0,<3"

[target.linux-64.dependencies]
pyg = ">=2.5.2,<3"

# This is to prevent the following error https://github.com/prefix-dev/pixi/issues/346#issuecomment-2094906047
[system-requirements]
libc = { family="glibc", version="2.26" }
